# -*- coding: utf-8 -*-
"""Data_Extraction.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WcWdkid5KVsUDXwaTaLuhzpMs5G39X_C
"""

pip install --upgrade google-api-python-client

import csv
from googleapiclient.discovery import build

# Replace the following values with your API key and the video ID
api_key = '***********'
video_id = 'lnS6v5frTx9A'

youtube = build('youtube', 'v3', developerKey=api_key)

def get_video_comments(service, **kwargs):
    comments = []
    results = service.commentThreads().list(**kwargs).execute()

    while results:
        for item in results['items']:
            comment = item['snippet']['topLevelComment']['snippet']['textDisplay']
            comments.append(comment)

        # Check if another page of comments exists
        if 'nextPageToken' in results:
            kwargs['pageToken'] = results['nextPageToken']
            results = service.commentThreads().list(**kwargs).execute()
        else:
            break

    return comments

comments = get_video_comments(youtube, part='snippet', videoId=video_id, textFormat='plainText')

# Specify the filename for your CSV file
filename = 'vid10.csv'

# Writing comments to a CSV file
with open(filename, mode='w', newline='', encoding='utf-8') as file:
    writer = csv.writer(file)
    writer.writerow(['Comment'])  # Writing header
    for comment in comments:
        writer.writerow([comment])  # Writing each comment as a row

print(f'Successfully written {len(comments)} comments to {filename}')

















